import pathlib

small_sentences_fr = [
    "JE N'AI D'YEUX QUE POUR TOI, L'AMOUR REND AVEUGLE N'EST-CE PAS ?",
    "LA VIE EST UNE ETRANGE ENTREPRISE, PLEINE DE RISQUES ET SANS BUT REVELE.",
    "LA CRYPTOGRAPHIE EST UNE SUPERBE DISCIPLINE ET EGALEMENT LE REFLET DE NOS LIMITES.",
    "JULES N'A PAS RECU DE CEASAR CETTE ANNEE, PERSONNE NE SAIT SI ON LE REVERA A CANNES.",
    "LA TELEVISION REND BETE ET MECHANT SURTOUT LES EMISSIONS FAITES PAR DES CONS POUR LES CONS.",
]

small_text_fr = [
    file.read_text(encoding="utf-8")
    for file in pathlib.Path("./pysgrs/resources/texts/fr/").glob("*.txt")
]
